"""add-owner-to-anonymous-identify

Revision ID: 24216e69f8a4
Revises: b84160020bf3
Create Date: 2024-08-21 16:17:18.653703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24216e69f8a4'
down_revision: Union[str, None] = 'b84160020bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anonymous_identify', sa.Column('owner_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'anonymous_identify', 'classic_identify', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'anonymous_identify', type_='foreignkey')
    op.drop_column('anonymous_identify', 'owner_id')
    # ### end Alembic commands ###
