"""init

Revision ID: 498e7422a676
Revises: 
Create Date: 2024-08-20 19:02:14.239040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from hiccup.db.user import user_id_sequence

# revision identifiers, used by Alembic.
revision: str = '498e7422a676'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(sa.schema.CreateSequence(user_id_sequence))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_identify',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('user_id_seq')"), nullable=False),
    sa.Column('public_key', sa.LargeBinary(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anonymous_identify_public_key'), 'anonymous_identify', ['public_key'], unique=True)
    op.create_table('classic_identify',
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('user_id_seq')"), nullable=False),
    sa.Column('user_name', sa.String(length=32), nullable=False),
    sa.Column('password', sa.LargeBinary(length=64), nullable=False),
    sa.Column('salt', sa.LargeBinary(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classic_identify_user_name'), 'classic_identify', ['user_name'], unique=True)
    op.create_table('virtual_server',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_token',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('anonymous_user_id', sa.BigInteger(), nullable=True),
    sa.Column('classic_user_id', sa.BigInteger(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('((anonymous_user_id IS NOT NULL AND classic_user_id IS NULL) OR (anonymous_user_id IS NULL AND classic_user_id IS NOT NULL))', name='check_anonymous_or_classic_user'),
    sa.ForeignKeyConstraint(['anonymous_user_id'], ['anonymous_identify.id'], ),
    sa.ForeignKeyConstraint(['classic_user_id'], ['classic_identify.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_token_token'), 'auth_token', ['token'], unique=True)
    op.create_table('channel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('joinable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['virtual_server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel')
    op.drop_index(op.f('ix_auth_token_token'), table_name='auth_token')
    op.drop_table('auth_token')
    op.drop_table('virtual_server')
    op.drop_index(op.f('ix_classic_identify_user_name'), table_name='classic_identify')
    op.drop_table('classic_identify')
    op.drop_index(op.f('ix_anonymous_identify_public_key'), table_name='anonymous_identify')
    op.drop_table('anonymous_identify')
    # ### end Alembic commands ###
    op.execute(sa.schema.CreateSequence(user_id_sequence))
