"""allow_invalid_alias

Revision ID: faf1966c992b
Revises: dd4117cc2b34
Create Date: 2024-08-31 21:21:59.410689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf1966c992b'
down_revision: Union[str, None] = 'dd4117cc2b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_server_alias', sa.Column('valid', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_server_alias', 'valid')
    # ### end Alembic commands ###
